src/vzctl-actions.c: compile fix
After commit 9a9bc8a we have this:

vzctl-actions.c: In function ‘run_action’:
vzctl-actions.c:1274:24: error: ‘MS_BIND’ undeclared (first use in this function)
vzctl-actions.c:1274:24: note: each undeclared identifier is reported only once for each function it appears in

Signed-off-by: Kir Kolyshkin <kir@openvz.org>