vzctl restore: fix wrt set_console
Commit 10bc885 adds SET_CONSOLE script. The problem is we should not
run it when restoring a container because
 (1) there is no need to
 (2) vps_exec_scripts closes an fd which is used as lock fd for the kernel

As a result of (2), we have this bug:

		undump...
	Adding IP address(es): 10.1.121.110
	Running: /usr/libexec/vzctl/scripts/vps-net_add
	Setting CPU units: 1000
	Running container script: /etc/vz/dists/scripts/set_console.sh
	Container restore failed (try to check kernel messages, e.g. "dmesg |
	tail")
	Killing container ...
	Restore error, undump failed: Operation canceled
	Error: CPT: lock fd is closed incorrectly: -125
	Container was stopped

Add a check for SKIP_CONFIGURE flag.

Signed-off-by: Kir Kolyshkin <kir@openvz.org>