vzmigrate: fix for offline migration of ploop CT
The problem:
	If you try to migrate stopped CT with ploop layout than vzmigrate
	does not detect ploop support:

	vzmigrate 123.123.123.123 ctid
	Preparing remote node
	cat: /sys/block//pstate/top: No such file or directory
	Error: Can't get ploop information

The cause:
	The code was trying to find out ploop top delta file in order
	to exclude it from the first rsync. It failed because the CT
	is stopped and thus ploop is not mounted.

The solution:
	Only try getting ploop info for the running container.

http://bugzilla.openvz.org/2316

Reported-by: Paparaciz <helpaz@gmail.com>
Signed-off-by: Kir Kolyshkin <kir@openvz.org>