vzctl: fix a compilation warning about capget()
The following compilation warning occurs
after commit 0d6bfad92c7cb6a193801ce8dac3a0dc64396ca8:

  cap.c: In function 'set_cap':
  cap.c:168: warning: implicit declaration of function 'capget'

capget prototype is in sys/capability.h; however we can't include it
since sys/capability.h conflicts with linux/capability.h

Put capget() prototype directly into cap.c

Signed-off-by: Kir Kolyshkin <kir@openvz.org>