bin/vzubc: fix -i/-r modes for 0th beancounter
Problem:
 # ./vzubc -i -c -r -q 0
 Error: can not use relative/incremental modes: BCID is unknown

Cause: commit 50c173f4871e

Solution: fix check for bcid to be less than zero, initialize bcid
to -1 at BEGIN.

Signed-off-by: Kir Kolyshkin <kir@openvz.org>