Fix vzctl and vzlist linking with ld-2.22
Get error:
libtool: link: i586-alt-linux-gcc -DSBINDIR=\"/usr/sbin\"
-DPKGCONFDIR=\"/etc/vz\" -DPKGDATADIR=\"/usr/share/vzctl\"
-DPKGLIBDIR=\"/usr/lib/vzctl\" -pipe -Wall -g -O2 -march=i586
-mtune=i686 -fno-strict-aliasing -Wall -Wpointer-arith -Wcast-qual
-Winline -Wextra -Wcast-align -Wno-unused-parameter
-Wno-missing-field-initializers -D_FILE_OFFSET_BITS=64 -o .libs/vzctl
enter.o modules.o snapshot.o vzctl-actions.o vzctl.o
../src/lib/.libs/libvzctl.so -ldl -lutil -lsetproctitle
/usr/bin/ld: snapshot.o: undefined reference to symbol
'ploop_delete_snapshot'
/usr/bin/ld: note: 'ploop_delete_snapshot' is defined in DSO
/usr/lib/libploop.so so try adding it to the linker command line
/usr/lib/libploop.so: could not read symbols: Invalid operation
collect2: ld returned 1 exit status
make[2]: *** [vzctl] Error 1
make[2]: Leaving directory `/usr/src/RPM/BUILD/vzctl-3.2/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/usr/src/RPM/BUILD/vzctl-3.2/src'
make: *** [all-recursive] Error 1
make: Leaving directory `/usr/src/RPM/BUILD/vzctl-3.2'
error: Bad exit status from /usr/src/tmp/rpm-tmp.83161 (%build)

With regard to:
binutils/ld/NEWS:
Changes in 2.22:
* --copy-dt-needed-entries is no longer enabled by default.  Instead
  --no-copy-dt-needed-entries is the default.

The behavior was changed and leads to an error.

Reference on the subject:
  http://fedoraproject.org/wiki/UnderstandingDSOLinkChange