ploop env.c: fix a warning
  CC     env.lo
env.c:701:10: warning: implicit declaration of function 've_private_is_ploop' is
      invalid in C99 [-Wimplicit-function-declaration]
        ploop = ve_private_is_ploop(res->fs.private);
                ^
This is an addition to commit f380a3c

Signed-off-by: Kir Kolyshkin <kir@openvz.org>