create.c: fix warnings compiling w/o ploop
Fix these:

>   CC       create.lo
> create.c: In function 'cleanup_umount_ploop':
> create.c:108:2: warning: implicit declaration of function
> 'vzctl_umount_image' [-Wimplicit-function-declaration]
> create.c: In function 'fs_create':
> create.c:132:37: warning: unused variable 'ploop_ch' [-Wunused-variable]
> create.c: At top level:
> create.c:106:13: warning: 'cleanup_umount_ploop' defined but not used
> [-Wunused-function]

This is an addition to commit 971dc84c.

Signed-off-by: Kir Kolyshkin <kir@openvz.org>