vzethdev is not loaded during a node start by /etc/init.d/vz
After upgrading to vzctl-3.0.18 during a node start vzethdev kernel
module is not loaded by /etc/init.d/vz script, consequently VEs with
veth does not start:

Configure veth devices: veth29.0 veth29.1
Error: veth feature is not supported by kernel
VE start failed

In commit f09fd723bbe70d98b772bd9d13fdf844d14cad59 vzethdev
moved from MODULES_OTHER to NET_MODULES and this caused the problem
that the following check:

if ip addr list | grep -q "venet0:.*UP"; then
    return 0
fi

is done before vzethdev is loaded...

This patch forces to try to load kernel modules at the beginning of VE
networking start.

http://forum.openvz.org/index.php?t=tree&goto=14942&#msg_14942

[kir@openvz.org: cleaned up the changelog entry]