Make the "UB parameter not set" error text more clear.
(1) Add 'required' because the parameter is obligatory.
(2) Add 'Error' because this is indeed an error.

Before:
	UB parameter kmemsize not set
	UB parameter lockedpages not set

After:
	Error: required UB parameter kmemsize not set
	Error: required UB parameter lockedpages not set

Signed-off-by: Kir Kolyshkin <kir@openvz.org>