vzmigrate: fix check for IPs when there are none
From the original bug report:

> vzmigrate fails to migrate VPS when it has no IP addresses. It says IP
> address is already used on destination node, which is not true.
>
> # vzmigrate destination 999
> Starting migration of CT 999 to destination
> Error: IP address(es) already in use on destination node
>
> This worked fine in vzctl 4.2. It is not working in vzctl 4.3.1.

This bug was introduced by commit e96417c.

https://bugzilla.openvz.org/2620

Reported-by: Jakub Skokan <skokan.jakub@gmail.com>
Signed-off-by: Kir Kolyshkin <kir@openvz.org>