Fixed compilation with libcgroup-0.37-r2
Fix the following bug:
> cgroup.c: In function ‘hackish_empty_container’:
> cgroup.c:442:8: error: ‘ECGNONEMPTY’ undeclared (first use in this
> function)
> cgroup.c:442:8: note: each undeclared identifier is reported only once
> for each function it appears in

Since libcgroup error codes are not #defines, we can't resort to
the usual #ifndef trick. Therefore, let's move error printing to
hackish_empty_container() and return VZ_STOP_ERROR code (which
is inconsistent but works with libcgroup-0.37).

http://bugzilla.openvz.org/2370

Cc: Glauber Costa <glommer@parallels.com>
Reported-by: Maksim Melnikau <maxposedon@gmail.com>
Signed-off-by: Kir Kolyshkin <kir@openvz.org>