Fix vzctl set --setmode restart error message
For a command like
	vzctl set 123 --feature nfs:on --setmode restart
the error message was like:

	it's impossible to use restart mode without --save

Changed to:

	Error: --setmode restart doesn't make sense without --save flag

Signed-off-by: Kir Kolyshkin <kir@openvz.org>