src/lib/vzfeatures.c: fix compilation with older headers
When trying to build vzctl on a CentOS 5 system, got this (see below).
The fix is to move

 #include <linux/vzcalluser.h>

to be below the

 #include "util.h"

so that various defines and typedefs won't clash.

Aaaand finally, here's the error message:

  CC     vzfeatures.lo
In file included from /usr/include/stdlib.h:438,
                 from ../../include/util.h:21,
                 from vzfeatures.c:23:
/usr/include/sys/types.h:52: error: conflicting types for ‘ino_t’
/usr/include/linux/types.h:14: error: previous declaration of ‘ino_t’
was here
/usr/include/sys/types.h:62: error: conflicting types for ‘dev_t’
/usr/include/linux/types.h:13: error: previous declaration of ‘dev_t’
was here
/usr/include/sys/types.h:67: error: conflicting types for ‘gid_t’
/usr/include/linux/types.h:27: error: previous declaration of ‘gid_t’
was here
/usr/include/sys/types.h:72: error: conflicting types for ‘mode_t’
/usr/include/linux/types.h:15: error: previous declaration of ‘mode_t’
was here
/usr/include/sys/types.h:77: error: conflicting types for ‘nlink_t’
/usr/include/linux/types.h:16: error: previous declaration of ‘nlink_t’
was here
/usr/include/sys/types.h:82: error: conflicting types for ‘uid_t’
/usr/include/linux/types.h:26: error: previous declaration of ‘uid_t’
was here
/usr/include/sys/types.h:90: error: conflicting types for ‘off_t’
/usr/include/linux/types.h:17: error: previous declaration of ‘off_t’
was here
In file included from /usr/include/sys/types.h:133,
                 from /usr/include/stdlib.h:438,
                 from ../../include/util.h:21,
                 from vzfeatures.c:23:
/usr/include/time.h:105: error: conflicting types for ‘timer_t’
/usr/include/linux/types.h:22: error: previous declaration of ‘timer_t’
was here
In file included from /usr/include/sys/types.h:220,
                 from /usr/include/stdlib.h:438,
                 from ../../include/util.h:21,
                 from vzfeatures.c:23:
/usr/include/sys/select.h:78: error: conflicting types for ‘fd_set’
/usr/include/linux/types.h:12: error: previous declaration of ‘fd_set’
was here
In file included from /usr/include/stdlib.h:438,
                 from ../../include/util.h:21,
                 from vzfeatures.c:23:
/usr/include/sys/types.h:248: error: conflicting types for ‘blkcnt_t’
/usr/include/linux/types.h:114: error: previous declaration of
‘blkcnt_t’ was here
make[2]: *** [vzfeatures.lo] Error 1

Signed-off-by: Kir Kolyshkin <kir@openvz.org>