ct_env_create_real(): don't use O_CLOEXEC
Replace O_CLOEXEC flag to open with a separate fcntl(FD_CLOEXEC)
call, since otherwise we can't be compiled on older distros:

hooks_ct.c: In function 'ct_env_create_real':
hooks_ct.c:427: error: 'O_CLOEXEC' undeclared (first use in this
function)
hooks_ct.c:427: error: (Each undeclared identifier is reported only once
hooks_ct.c:427: error: for each function it appears in.)

Signed-off-by: Kir Kolyshkin <kir@openvz.org>