vzcfgvalidate: do not check disk quota params if disk quota is off
If DISK_QUOTA is set to "no" (globally or for this particular container)
do not check disk quota parameters or complain that they are absent.

Without this patch and quota disabled and no quota values
in container's config, the following errors occur:

  $ vzcfgvalidate 201.conf
  Error: parameter diskspace not found
  Error: parameter diskinodes not found

http://bugzilla.openvz.org/833

Signed-off-by: Kir Kolyshkin <kir@openvz.org>