src/vzeventd.c: fix compile on CentOS 4
Old and ancient CentOS4 glibc-kernheaders package provides
/usr/include/linux/netlink.h which does not #include <linux/types.h>
so we have to do it explicitly, otherwise:

  CC     vzeventd.o
In file included from vzeventd.c:25:
/usr/include/linux/netlink.h:22: error: syntax error before "__u32"
/usr/include/linux/netlink.h:28: error: syntax error before "__u32"
/usr/include/linux/netlink.h:30: error: syntax error before "nlmsg_flags"
/usr/include/linux/netlink.h:31: error: syntax error before "nlmsg_seq"
/usr/include/linux/netlink.h:32: error: syntax error before "nlmsg_pid"
/usr/include/linux/netlink.h:82: error: field `msg' has incomplete type
vzeventd.c: In function `prepare_read_events':
vzeventd.c:212: error: storage size of 'sa' isn't known
vzeventd.c:212: warning: unused variable `sa'
make[2]: *** [vzeventd.o] Error 1

Signed-off-by: Kir Kolyshkin <kir@openvz.org>